QS.Project/Project.Domain/EntityConstructorParam.cs
QS.Project/Project.Domain/EntityUoWBuilder.cs
QS.Project/QS.Project.csproj
QS.Project/ViewModels/EntityTabViewModelBase.cs

В соответствии с обсуждением #14
Есть аналогичная ветка с исправлениями в водовозе.
Кстати. Так как у нас теперь версии, может я удалю старый класс EntityConstructorParam ? Вы когда будете перезжать на более свежую версию подправите у себя.

Рефакторинг EntityConstructorParam 

---

QS.LibsTest/Project.Journal/ThreadDataLoaderTest.cs
QS.Project/Project.Journal/DataLoader/ThreadDataLoader.cs

Старый код, в некоторых ситуациях прекращал работу, не сбрасывая состояние LoadInProgress и не вызывая события изменения для внешнего кода.
В новой реализации такие ситуации исключены. Дополнительно убрал переключения состояния, между запросам, когда код под завершению предыдущего понимает что надо начинать работу над следущим.  Теперь в этот момент отсутствует переключение LoadInProgress в false и потом обратно в true.

Переработана логика отображения состояния загрузки через свойство LoadInProgress

---

QS.Project.Gtk/Tdi.Gtk/TDIMain.cs
QS.Project.Gtk/Tdi.Gtk/TabVBox.cs
QS.Project.Gtk/Tdi.Gtk/TdiNotebook.cs
QS.Project.Gtk/Tdi.Gtk/TdiSliderTab.cs

Еще один небольшой шаг к более повсеместному использованию DI.
Тот же вопрос, если мы теперь испозуем версии, может я могу сразу удалить старое статическое поле?

Резольвер ITDIWidgetResolver используем через DI

---

QS.Project.Gtk/Widgets.GtkUI/DatePicker.cs
QSWidgetLib/DatePicker.cs

Поменяно в старой библиотеке (т.к. очень хочется видеть изменения в мониторинге) и в новой.

В DatePicker добавил ползунок для более удобного указания времени

---

.gitignore
QS.Project/Project.Journal/DataLoader/DynamicQueryLoader.cs
QS.Project/Project.Journal/DataLoader/IDataLoader.cs
QS.Project/Project.Journal/DataLoader/IQueryLoader.cs
QS.Project/Project.Journal/DataLoader/ThreadDataLoader.cs
QS.Project/Project.Journal/EntityJournalViewModelBase.cs

Автоматический выбор нового документа в журналах
Переделка реквеста : https://github.com/QualitySolution/QSProjects/pull/17

Автоматический выбор нового документа в журналах 

---

QS.Project/DomainModel/Tracking/UowWatcher.cs

Не хватает этих данных при анализе логов пользователей в случае утечек.

При завершении работы UoW, пишем в лог где был создан этот UoW.

---

QSWidgetLib/ValidatedEntry.cs

Переделка https://github.com/QualitySolution/QSProjects/pull/39

Добавлена проверка на спец.символы при вводе email

---

QS.Project.Gtk/QS.Project.Gtk.csproj
QS.Project.Gtk/Views.GtkUI/WidgetViewBase.cs

Класс не рабоает с Entity и не как его не использует

EntityWidgetViewBase переименован в WidgetViewBase

---

QS.Project.Gtk/gtk-gui/QS.Widgets.GtkUI.DateRangePicker.cs
QS.Project.Gtk/gtk-gui/QS.Widgets.GtkUI.TimeRangePicker.cs
QS.Project.Gtk/gtk-gui/gui.stetic

Подстройка ui под новый id ресурса ( https://github.com/QualitySolution/QSProjects/pull/45 )

fix : исправил id ресурса в UI элементах

---

Modules/CustomFields/QSCustomFields.csproj
Modules/QS.Banks/QS.Banks.csproj
Modules/QS.BusinessCommon/QS.BusinessCommon.csproj
Modules/QS.Contacts/QS.Contacts.csproj
Modules/QSAttachment/QSAttachment.csproj
Modules/QSBanks/QSBanks.csproj
Modules/QSBusinessCommon/QSBusinessCommon.csproj
Modules/QSContacts/QSContacts.csproj
Modules/QSCurrency/QSCurrency.csproj
QS.HistoryLog/QS.HistoryLog.csproj
QS.LibsTest/QS.LibsTest.csproj
QS.Project.Gtk/QS.Project.Gtk.csproj
QS.Project/QS.Project.csproj
QS.Report/QS.Report.csproj
QS.Testing/QS.Testing.csproj
QS.Updater/QS.Updater.csproj
QS.Utilities/QS.Utilities.csproj
QSExtraGammaWidgets/QSExtraGammaWidgets.csproj
QSFNS/QSFNS.csproj
QSOrmProject/QSOrmProject.csproj
QSOsm/QSOsm.csproj
QSOsmBaseScripts/QSOsmBaseScripts.csproj
QSOsmService/QSOsmService.csproj
QSProjectsLib.sln
QSReport/QSReport.csproj
QSSaaS/QSSaaS.csproj
QSScan/QSScan.csproj
QSTelemetry/QSTelemetry.csproj

В мастере как бы 1.1,  есть отдельная ветка 1.0
В планах на 1.1 до конца реализовать новый подход к диалогам. Потом уже этот код пытаться не трогать.

Проставил версию библиотек 1.1

---

QS.Project.Gtk/gtk-gui/QS.Widgets.GtkUI.TimeRangePicker.cs
QS.Project.Gtk/gtk-gui/gui.stetic

fix: https://github.com/QualitySolution/QSProjects/pull/48
Оставил ненужный пробел в id

fix: убрал ненужные пробелы из id ресурса в виджете выбора времени

---

QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
QS.Project/Project.Journal/EntitySelector/IEntityAutocompleteSelector.cs
QS.Project/Project.Journal/SimpleEntityJournalViewModel.cs
QS.Project/Project.Journal/SingleEntityJournalViewModelBase.cs

Переделка https://github.com/QualitySolution/QSProjects/pull/35

Fix автодополнения

---

QS.Project/ViewModels/EntityTabViewModelBase.cs

когда, оказывается что поле Title или Name возвращает null.
Ну и дополнительно решил что и пустая строка тоже плохо, лучше отображать название сущности.

Исправлено падение при открытии вкладки

---

QS.Project.Gtk/QS.Project.Gtk.csproj
QS.Project.Gtk/Widgets/ValidatedEntry.cs
QSWidgetLib/ValidatedEntry.cs

Удалил из него ввод телефонного номера, так как есть отдельный более навороченный PhoneEntry.
Так же удалил в том числе из старого класса single_word
Этот режим, не работал, и вообще нигде не использовался.

Перенес ValidateEntry в QS.Project.Gtk

---

QS.LibsTest/Utilities/DataRangeTest.cs
QS.Utilities/Dates/DateRange.cs

Так же добавлен тесты основных случаев.

Добавлена возможность вычислять количество месяцев между произвольными датами.

---

QS.LibsTest/QS.LibsTest.csproj
QS.LibsTest/Utilities/Text/NaturalStringComparerTest.cs
QS.Utilities/QS.Utilities.csproj
QS.Utilities/Text/NaturalStringComparer.cs
QSOsm/QSOsm.csproj
QSOsm/Widgets/HouseEntry.cs
QSProjectsLib/Helpers/StringWorks.cs

Перенес NaturalStringComparer в библиотеку утилит, тем самым отвязал OSM от старой библиотеки проектов.
Исправил падение IndexOutOfRangeException

Перенес NaturalStringComparer в новые библиотеки + исправил ошибку

---

QS.Project.Gtk/QS.Project.Gtk.csproj
QS.Project.Gtk/Widgets/ProgressWidget.cs
QS.Project/Dialog/IProgressBarDisplayable.cs
QS.Project/QS.Project.csproj

Реализация по больше части перенесена из водовоза.
Просто реализована на базе виджета чтобы было удобнее использовать и находилось все в одном классе.

Добавлен ProgressWidget на Gtk реализующий IProgressBarDisplayable

---

QS.Project.Gtk/Navigation/GtkWindowsNavigationManager.cs
QS.Project.Gtk/Navigation/TdiNavigationManager.cs
QS.Project/Navigation/NavigationManagerBase.cs
QS.Project/QS.Project.csproj
QS.Project/ViewModels/Dialog/ModalDialogViewModelBase.cs

Позволяет реализовывать ViewModel которые открываются как модальные окна.

Добавлена реализация открытия ViewModel в модальном диалоге.

---

QS.Project.Gtk/QS.Project.Gtk.csproj
QS.Project.Gtk/Views/Resolve/ClassNamesBaseGtkViewResolver.cs
QS.Project.Gtk/Views/Resolve/IGtkViewResolver.cs
QS.Project.Gtk/Views/Resolve/RegisteredGtkViewResolver.cs
QS.Project.Gtk/Views/ViewBase.cs

Соответствующим образом подправлен резольвер View.

Добавлен базовый класс для простого вью который не диалог

---

QS.Project/Project.Journal/Search/SearchHelper.cs

Исправлена ошибка ввода в строку поиска виджета "Организации" строки, большой длины, состоящей из цифр, с помощью правильного определения типа введенных данных

Исправлен парс строки при вводе символов в строку поиска

---

QSOsm/IOsmService.cs
QSOsm/Loaders/CitiesDataLoader.cs
QSOsm/Loaders/HousesDataLoader.cs
QSOsm/Loaders/OsmDataLoader.cs
QSOsm/Loaders/StreetsDataLoader.cs
QSOsm/QSOsm.csproj
QSOsm/Widgets/CityEntry.cs
QSOsm/Widgets/HouseEntry.cs
QSOsm/Widgets/StreetEntry.cs
QSOsmService/OsmService.cs

Выделил загрузку данных из Osm в отдельные классы +
Добавил возможность загружать ограниченные объемом и критериями данные из Osm

Загрузка данных из OsmService

---

QS.Project.Gtk/Project.Dialogs.GtkUI/UserDialog.cs
QS.Project.Gtk/Widgets.GtkUI/UserPermissionWidget.cs
QS.Project.Gtk/Widgets.GtkUI/UserPresetPermissionWidget.cs

Там где нужен можно записать в функцию создания виджетов для прав прописать

Убрал создание виджета предустановленных прав в диалоге пользователя по умолчанию

---

QS.Project.Gtk/Navigation/GtkWindowsNavigationManager.cs
QS.Project.Gtk/Navigation/TdiNavigationManager.cs
QS.Project.Gtk/QS.Project.Gtk.csproj
QS.Project.Gtk/Views/Dialog/WindowSizeAttribute.cs

Если view открывается в отдельном окне.

Добавил атрибут для класса View позволяющий задать размеры окна по умолчанию.

---

QS.Project/QS.Project.csproj
QS.Project/ViewModels/Control/EEVM/CommonEEVMBuilder.cs
QS.Project/ViewModels/Control/EEVM/CommonEEVMBuilderFactory.cs
QS.Project/ViewModels/Control/EEVM/EntityEntryViewModel.cs
QS.Project/ViewModels/Control/EEVM/IEEVMBuilderParameters.cs
QSOrmProject/QSOrmProject.csproj
QSOrmProject/ViewModels/Control/EEVM/ILegacyEEVMBuilderParameters.cs
QSOrmProject/ViewModels/Control/EEVM/LegacyEEVMBuilder.cs
QSOrmProject/ViewModels/Control/EEVM/LegacyEEVMBuilderFactory.cs
QSOrmProject/packages.config

Более детальное описание в комитах.

Рефакториг постоителя для EE

---

QS.Project.Gtk/Views/Control/EntityEntry.cs
QS.Project/ViewModels/Control/EEVM/EntityEntryViewModel.cs
QS.Project/ViewModels/Control/EEVM/IEntityEntryViewModel.cs

+ доп описание свойств интрфейса.

Добавил доступность событий через интерфейс.

---

QSSupportLib/QSSupportLib.csproj

Вроде получилось. покрайней мере на тестовых ветках не падало.
Хотя конечно эти ссылки автоматом добавлялись, то есть это внешние зависимости их тянут.

Попытка поправить проблему со сборкой.

---

QS.Testing/Deletion.Testing/DeleteConfigTestBase.cs

Важные для корректного отображения в диалоге удаления.

Добавлен помощник тестирования которые позволяет находить незаполненные AppellativeAttribute

---

QS.LibsTest/DomainModel/NotifyChange/NotifyChangeIntegratedTest.cs
QS.Project/DomainModel/NotifyChange/Conditions/SelectionConditions.cs
QS.Project/DomainModel/NotifyChange/Conditions/SingleEntityCondition.cs

Так же +3 теста основных случаев.

Добавлена возможность при подписке указывать условия отбора событий.

---

QS.Project.Gtk/Widgets.GtkUI/DatePicker.cs
QS.Project.Gtk/Widgets.GtkUI/DateRangePicker.cs

Удалил настройку DefaultWidthRequest. Добавил настройку SetCurrentDateByDefault в DateRangePicker (По умолчанию true)
Добавил настройку CalendarFontSize для размера шрифта календаря

Изменения в DatePicker и DateRangePicker

---

QS.Project/Deletion/ViewModels/DeletionViewModel.cs
QSOrmProject/OrmMain.cs

Не возможность выйти из цикла если нажать на крестик в окне удаления. и не жрать CPU в момент отображения диалога.

Исправил баг работы переписанного удаления.

---

QSOsm/Loaders/CitiesDataLoader.cs
QSOsm/Loaders/HousesDataLoader.cs
QSOsm/Loaders/StreetsDataLoader.cs
QSOsm/Widgets/CityEntry.cs
QSOsm/Widgets/HouseEntry.cs
QSOsm/Widgets/StreetEntry.cs

Добавлена проверка на уничтоженный виджет в Street, House и Cities Entry

Исправление загрузки данных в наследниках OsmDataLoader

---

QS.LibsTest/Navigation/TdiNavigationManagerTest.cs
QS.Project.Gtk/Navigation/TdiNavigationManager.cs

Исправлен баг открытия ViewModel из диалога расположенном в нутри слайдера и неявляющегося журналом.

---

QSProjectsLib/AssemblyAttributes.cs
QSProjectsLib/Login.cs
QSProjectsLib/QSMain.cs

Переделаны окно логина и о программе, для отображения имени редакции.

В атрибут редакции добавлено поле с названием редакции.

---

QS.Project.Gtk/Journal.GtkUI/JournalView.cs

До этого срабатывала только педварительная установка режима, после создания View режим уже сменить было нельзя.

Исправлена установка режима выбора в журнале.

---

QS.Project/DomainModel/Entity/PropertyChangedAlsoAttribute.cs
QS.Project/DomainModel/Entity/PropertyChangedBase.cs

Несколько свойств можно добавлять и одним, но несколько атрибутов друг над другом выглядят более читаемо. Поэтому изменение чисто для читаемости кода.

Реализовал возможность добавлять несоколько атрибутов PropertyChangedAlsoAttribute

---

QS.Project.Gtk/Navigation/TdiNavigationManager.cs
QS.Project/Navigation/INavigationManager.cs

И добавлен еще один метод с двумя аргументами.

В интрефейс совместимости добавлена возможность создавать табы над viewModel

---

QS.Project/Project.Journal/DataLoader/AnyDataLoader.cs
QS.Project/QS.Project.csproj

Позволяющий в коде журнала сформироваль любые данные. Например полностью программно посторить список.

Добавил простой загрузчик журнала.

---

QS.Project/ViewModels/Control/EEVM/EntityEntryViewModel.cs
QS.Project/ViewModels/Control/EEVM/IEntityEntryViewModel.cs
QS.Project/ViewModels/Control/EEVM/JournalViewModelSelector.cs
QSOrmProject/ViewModels/Control/EEVM/ILegacyEEVMBuilderParameters.cs
QSOrmProject/ViewModels/Control/EEVM/LegacyEEVMBuilder.cs
QSOrmProject/ViewModels/Control/EEVM/LegacyEEVMBuilderFactory.cs
QSOrmProject/ViewModels/Control/EEVM/OrmObjectDialogOpener.cs
QSOrmProject/ViewModels/Control/EEVM/OrmReferenceSelector.cs

В одном пул реквесте несколько проблем. Обединил в единый реквест.

Различные улучшения легаси билдера.

---

QS.Project/ViewModels/Control/EEVM/CommonEEVMBuilder.cs
QSOrmProject/ViewModels/Control/EEVM/LegacyEEVMBuilder.cs

Это позволит использовать механизм автоматической настройки контрола, в ситуации когда отсутствует или ViewModel журнала или ViewModel диалога.

Не падаем если не нашли вью модел.

---

QS.Project/Navigation/IPage.cs
QS.Project/Navigation/PageBase.cs

Для удобства прикрепления к открытому диалогу какой либо внешней информации.

Добавил свойство Tag на Page

---

QS.Report/QS.Report.csproj
QS.Report/RDLReportsHashGenerator.cs

ЧТобы отчеты с разными параметрами не пересекались.

Добавлен генератор хешей для отчетов.

---

QS.Project/DomainModel/Entity/DomainTreeNodeBase.cs

Добавлен статический метод получения корневого родителя сущности

---

QSProjectsLib/Login.cs

Скрывать пароль пользователя в exception

---

QSProjectsLib/UserInfo.cs

Если проекты при построении mainWindow пытаются проверить права. ТО может слудчит 2 ситуации:
- У рута нет прав, поэтому окно не построится а упадет.
- База еще не обновлена и прав в виде колонок еще нет в БД.

Исправляем падения связанные с правами.

---

QS.Project/Navigation/ClassNamesHashGenerator.cs

Ранее не учитывался id поэтому нельзя было открыть 2 вкладки одного типа.

Исправлена расчет Hash для TDI вкладок.

---

QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
QS.Project.Gtk/Widgets.GtkUI/RepresentationEntry.cs
QSExtraGammaWidgets/yWidgets/yEntryReference.cs
QSExtraGammaWidgets/yWidgets/yEntryReferenceVM.cs
QSOrmProject/Widgets/EntryReference.cs
QSOrmProject/Widgets/EntryReferenceVM.cs

Чтобы видно было в варнингах сколько еще осталось старого кода.

Пометил все старые виджеты выбора из справочника устаревшими

---

QSOrmProject/OrmMain.cs

Добавлен функционал открытия ViewModel для TEnitity

Упрощены указания типов

---

QS.HistoryLog/HibernateTracker.cs

В случае если название действия находится в списке - добавляется имя файла и строка из которой было вызвано изменение

Изменение формата лога действий

---

QS.HistoryLog/HibernateTracker.cs

Исправляет отсечение для Unix систем

Изменёна константа отсечения пути от имени файла

---

QS.Report.Gtk/QS.Report.Gtk.csproj
QS.Report.Gtk/Views/RdlViewerView.cs
QS.Report.Gtk/gtk-gui/gui.stetic
QS.Report.Gtk/packages.config
QS.Report/QS.Report.csproj
QS.Report/ReportInfo.cs
QS.Report/ViewModels/RdlViewerViewModel.cs
QS.Report/ViewModels/ReportParametersViewModelBase.cs
QS.Report/packages.config

Добавил механизм создания виджетов с параметрами отчета.

---

QSReport/MultipleDocumentPrinter.cs

Убирает печать RDL, если не поступило RDL документов

Проверка на необходимость печати RDL

---

QS.Project/Project.DB/IConnectionFactory.cs
QS.Project/Project.DB/MySqlConnectionFactory.cs
QS.Project/QS.Project.csproj

В результате отказа от предыдущего пул реквеста я пошел более простым путем фабрику оставил, так как они пригодилась. Остальное реализовалось просто привязкой создания соединений к скопу автофака, и созданием их через автофак. Таким образом вопрос со отдельными соединениями для разных потоках решился проще.

Фабрика и интерфейс для создания соединений.

---

QS.Osm/Loaders/CitiesDataLoader.cs
QS.Osm/Loaders/StreetsDataLoader.cs

Убирает выброс ошибки при запросах автозаполнения города и улицы

Обработка ошибок при отмете задачи

---

QS.Project.Gtk/Journal.GtkUI/JournalView.cs
QS.Project.Gtk/Journal.GtkUI/TreeViewColumnsConfigFactory.cs

См. документацию.
Дополнительно проверьте на всякий случай не поломались ли простые журналы на базе SimpleEntityJournalViewModelBase. У меня такие просто нигде не используются, поэтому не могу проверить.

Добавлена возможность регистрировать конфигурацию таблицы у которой есть возможность обратится к ViewModel журнала.

---

QS.Project/ViewModels/Control/EEVM/UowEntityAdapter.cs

Там где система отслеживания изначально не инициализирована, Инстанса не будет, Поэтому подписываться не на что, это доп опция виджета, он может работать без отслеживания изменений, поэтому не надо падать.

Не падаем если система отслеживания не активирована.

---

QS.Utilities/Text/TextSpinner.cs

Специально под винду. Половина из имеющихся не отображаются корректно на винде при дефолтных настройках.

Добавил несколько текстовых спинеров.

---

QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
QS.Project/Project.Journal/JournalViewModelBase.cs

Смена модификатора доступа и дополнение документации

Изменен модификатор доступа к методу с internal на protected

---

QS.LibsTest/QS.LibsTest.csproj
QS.LibsTest/TestNamespace/ViewModels/OneLevel/NumberName123987TestViewModel.cs
QS.LibsTest/TestNamespace/Views/OneLevel/NumberName123987TestView.cs
QS.LibsTest/Views/Resolve/ClassNamesBaseGtkViewResolverTest.cs
QS.Project.Gtk/Views/Resolve/ClassNamesBaseGtkViewResolver.cs

Исправлен баг резольва view в именах классов которых есть цифры.

---

QS.Project/Project.DB/NhDataBaseInfo.cs
QS.Project/Project.Versioning/IDataBaseInfo.cs

Пока достаточно кривое и не универсальное решение. Реализовано до момента более кардинальных изменений в демонстрационной версии.

Добавлена возможность получить информацию является ли база данных демонстрационной

---

QS.Project.Gtk/Tdi/TdiNotebook.cs

Добавлена реализация перемещения вкладок.
Добавлена пересортировка подчиненных вкладок.
Добавлена пересортировка при попытке положить вкладку между основной и подчиненными вкладками.

Перемещаемые вкладки в TdiNotebook

---

QS.Project.Gtk/Tdi/TdiNotebook.cs

Из-за обработки вклинивающихся в связку связанных вкладок появился баг подчиненных вкладок, исправлено в ПР

Исправлена ошибка перемещения подчиненных вкладок

---

QS.Project/Deletion/DeleteCore.cs
QS.Project/Project.Services/DeleteEntityGUIService.cs

Реализация так себе. Но там при текущем подходе сложно отловить закрытие модуля.

Убираю утечки uow, в модуле удаления.

---

QS.Project/DomainModel/NotifyChange/Conditions/SelectionConditions.cs
QS.Project/DomainModel/NotifyChange/EntityChangeEvent.cs

Например часто мы не хотим обрабатывать изменения сделанные своим же Uow.

Добавлена возможность исключить некторые сесии из уведомлений

---

QS.Project.Gtk/Journal.GtkUI/JournalView.cs

Заодно удалил безсмысленный метод RefreshSource

Добавил горячую клавишу F5 для обновления списка.

---

QSProjectsLib/EditConnection.cs
QSProjectsLib/gtk-gui/QSProjectsLib.EditConnection.cs
QSProjectsLib/gtk-gui/gui.stetic

Если не заполнены поля сервера или имени базы.

Не даем пользователю нажать на кнопку создания базы

---

QS.Project/DomainModel/Entity/EntityPermissions/EntityExtendedPermission/EntityPermissionExtendedBase.cs
QS.Project/DomainModel/Entity/EntityPermissions/EntityExtendedPermission/EntityUserPermissionExtended.cs
QS.Project/Project.Domain/TypeOfEntity.cs
QS.Project/Project.HibernateMapping/EntityPermissionExtendedBaseMap.cs

Переделал свойство PermissionExtendedType. Раньше Nhibernate в принципе не лез за override свойством в классе-наследнике

---

QS.Project/QS.Project.csproj
QS.Project/Validation/PasswordValidation/DefaultPasswordValidationSettings.cs
QS.Project/Validation/PasswordValidation/IPasswordValidationSettings.cs
QS.Project/Validation/PasswordValidation/IPasswordValidator.cs
QS.Project/Validation/PasswordValidation/PasswordValidator.cs
QS.Utilities/QS.Utilities.csproj
QS.Utilities/Text/StringValidationHelper.cs
QSProjectsLib/ChangePassword.cs
QSProjectsLib/UserInfo.cs
QSProjectsLib/gtk-gui/QSProjectsLib.ChangePassword.cs
QSProjectsLib/gtk-gui/gui.stetic

Создан отдельный класс валидации пароля и настроек к нему

Изменение валидации пароля в ChangePassword

---

QS.Project.Gtk/Tdi/TDIMain.cs
QS.Project.Gtk/Tdi/TdiNotebook.cs

Вроде этот(tdinotebook) файл был переведен на LF, но похоже, что в районе OnPageReordered опять поменялись окончания. VS Code при открытии файла отображает окончания как LF.~И откуда взялись конфликты что то тоже не понимаю.~ Конфликты исправились после первого коммита

Добавлен цветной префикс вкладок и метод для включения этого режима, а также режима перемещения вкладок

---

QS.Project.Gtk/Tdi/TdiNotebook.cs

+ Дефолтное значение для флага перемещения вкладок

Фикс подписки на события в случае, если выделение цветом не используется

---

QS.Project.Gtk/Widgets.GtkUI/NullableCheckButton.cs

Для задачи 2851 - матрицы прав складов. Оптимизация, чтобы не грузить множество картинок

Изменение загрузки с иконки на символ

---

QS.Project/Project.DB/MySQL57ExtendedDialect.cs
QS.Project/QS.Project.csproj

Думаю всё-таки лучше убрать зависимость от NHibernate.Spatial.Dialect

---

QSOrmProject/BindingsConverters.cs

Внимание возможно потребует изменения неймспейсов, если используется в ВВ.

Конвертер GuidToStringConverter перемещен в библиотеку Gamma

---

QS.Project/Project.Repositories/IMySqlPasswordRepository.cs
QS.Project/Project.Repositories/MySqlPasswordRepository.cs
QS.Project/ViewModels/ChangePasswordViewModel.cs

Старый был ненадёжный, а также требовал SELECT право на mysql базу
Ещё изменил проверку на равенство текущего и нового пароля чтобы не делать лишний запрос в базу

Изменил способ проверки текущего пароля пользователя

---

QS.Project/Project.DB/NhDataBaseInfo.cs
QS.Project/Project.Versioning/IDataBaseInfo.cs

Этот уникальный идентификатор базы. который можно генерить при первом запуске базы, он позволяет отслеживать и идентифицировать разные базы.

Добавлена возможность получить Guid базы

---

QS.Utilities/Numeric/PhoneFormatter.cs

Пока реальзован только один формат. В последствии можно добавить другие.

Добавлен валидатор формата телефона.

---

Modules/QSBanks/BanksUpdater.cs

Добавил проверку на наличие удаляемых кор счетов у р/сч
Если таковые есть, то обновляем их

3516 Ошибка при обновлении банков.

---

QS.LibsTest/Utilities/PhoneFormatterTest.cs
QS.Utilities/Numeric/PhoneFormatter.cs

Добавлен новый формат телефона +7XXXXXXXXXX

---

QS.Project.Gtk/Dialog/MessageDialogHelper.cs

Добавлено расширение диалога под сообщение.

Длинные сообщения теперь влезают в MessageDialog

---

QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs

После уничтожения entry прилетала ошибка

Исправление NullReferenceException

---

QS.Project/ViewModels/Control/EEVM/UowEntityAdapter.cs

Просто очищаем значение, в виджете.
Падоло в ситуации: есть диалог с полем выбора, там выбрана конкретная сущьность. Мы ее удаляем в этом диалоге падает попытка обновить объект

Не пытаемся обновить сущность в виджете справочников, если она была удалена

---

QS.LibsTest.Core/DomainModel/Entity/PropertyChangedBaseTest.cs
QS.LibsTest.Core/TestApp/Domain/Entity/PropertyChangedClass.cs
QS.LibsTest.Core/TestApp/Domain/Entity/PropertyChangedDescendantClass.cs
QS.LibsTest.Core/TestApp/Domain/Entity/PropertyChangedDescendantClass2.cs
QS.Project.Core/DomainModel/Entity/PropertyChangedBase.cs

+ Тесты этого и других случаев.

Исправление эксепшена  System.Reflection.AmbiguousMatchException : Ambiguous match found.

---

QS.Project.Gtk/Journal.GtkUI/JournalView.cs
QS.Project/Project.Journal/JournalViewModelBase.cs

Пока нет новых экшенов, добавил делегат для обновления состояния кнопок. В моем случае после нажатия.

Возможность обновления состояния кнопок в журнале в любой момент 

---

QS.Project.Core/Dialog/IProgressBarDisplayable.cs
QS.Project.Gtk/Widgets/ProgressWidget.cs

Добавлена возможность получать текущее значение

---

QSScan/QSScan.csproj
QSWidgetLib/QSWidgetLib.csproj

Обновлена версия QSScan и QSWidgetLib
Может не заработать без остальных пулл-реквестов

Обновление версии SDK до 4.6.1

---

QS.Report/ReportInfo.cs

Почищен код, сделано более читабельным.
Переменная connection string теперь инициализируется иначе.
В конструкторе, если не передан параметр все происходит как раньше.
Если задан параметр - параметр инициализирует сроку подключения.

Рефакторинг ReportInfo

---

QS.Report/ReportInfo.cs

Фоллбек не работает, так как применяется к результату выполнения функции
В то время как сама функция null

Исправление фикса NullRef

---

QS.Project.Gtk/Widgets.GtkUI/PhotoView.cs

Добавил проверку на наличие картинки

Исправление nullRefException

---

QS.Project/Print/SelectablePrintDocument.cs
QS.Project/QS.Project.csproj
QSReport/MultipleDocumentPrinter.cs

Перенес SelectablePrintDoc из проекта с ГТК и удалил ненужный метод, использующий его

Перенос SelectablePrintDoc

---

QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
QS.Project/Project.Journal/EntityJournalNodeBase.cs
QS.Project/Project.Journal/EntitySelector/IEntitySelector.cs

До открытия журнала из энтри не было возможности получить ноду для передачи в методы, если в evme уже был какой то subject. Приводило к ошибке при нажатии на "открыть"

Изменил реализацию открытия диалогов в EVME

---

QS.Project/Project.Journal/Search/SearchHelper.cs

+ В соседнем методе добавил поддержку Nulable int

Добавлена поддежка поиска как число по полям uint и unit? и int?

---

QS.Project.Gtk/Journal.GtkUI/JournalView.cs

Создал переменную виджета, чтобы ее дестроить, тем самым диспозился UoW

Исправления UnitOfWork

---

QS.Project/Project.Journal/SimpleEntityJournalViewModel.cs

Для простого журнала не находился нужный конструктор ноды.

Исправил открытие в EVME через простой журнал

---

QS.Project.Gtk/Widgets.GtkUI/UserEntityPermissionWidget.cs
QS.Project.Gtk/gtk-gui/QS.Widgets.GtkUI.UserEntityPermissionWidget.cs
QS.Project.Gtk/gtk-gui/gui.stetic

По задаче необходимо было добавить поиск на документы в диалог пользователя
Поиск быстрый, проект не нагружает

Поиск на документы в диалоге пользователя

---

QSProjectsLib/Login.cs
QSProjectsLib/QSProjectsLib.csproj
QSProjectsLib/gtk-gui/QSProjectsLib.Login.cs
QSProjectsLib/gtk-gui/gui.stetic

3767 Добавлены предупреждения при любом нажатии клавиш и перехода в текущее окно ввода пароля: если язык раскладки клавиатуры отличается от английского, если нажата клавиша CapsLock. 
Функционал активен только при текущей ОС = Windows, т.к. не удалось получить язык текущей раскладки клавиатуры для Linux.

Предупреждения в окне ввода пароля при включенной клавише CapsLock и не английской раскладке клавиатуры

---

QS.Project/ErrorReporting/HttpErrorReportSender.cs
QS.Project/ErrorReporting/HttpErrorReportingService.cs
QS.Project/ErrorReporting/IErrorReportSender.cs
QS.Project/ErrorReporting/IErrorReportingService.cs
QS.Project/ErrorReporting/ReportWorker.cs
QS.Project/QS.Project.csproj

Работает, но пришлось выеживаться с xml-кой. Не трогал data и service contract, так что работа сервиса не должна измениться. Старался максимально повторить отправляемый в оригинале пакет, ибо какие либо расхождения в xml приводили бы к ошибке сериализации или дальнейшей обработки, а неправильные заголовки в запросе роняли полностью службу.
https://github.com/QualitySolution/QSInside/pull/1

Переделал отправку ошибок на httpClient

---

Binding/Gamma.Binding/TreeModels/CellRenderers/NodeCellRendererCombo.cs
Binding/Gamma.Binding/TreeModels/ColumnConfig/ComboRendererMapping.cs

Убрал лишний каст к ноде в NodeCellRendererCombo;
Если в динамическом списке нет элементов - не выводим пустую менюшку;
Добавил EditedEvent к комбо в тривьюхе

Изменения к задаче 3802 Переработка оснований скидок

---

QS.Project.Gtk/Journal.GtkUI/JournalView.cs

Добавляем проверку на возможность запуска экшена при двойном клике в журнале

Изменения во вьюхе журнала

---

QS.LibsTest/Navigation/TdiNavigationManagerTest.cs
QS.Project.Gtk/Navigation/TdiNavigationManager.cs

Предыдущее изменение с параметром AlwaysNewPage для журнала, выловило другую проблему в навигаторе. Детали в коммите.
+ Тест для конкретно этого случая.

Исправление открытия подчерненных вкладок журнала из слайдера.

---

Binding/Gamma.Binding/Widgets/EnumCheckList.cs

Заменил IEnumerable на params
Добавил вызов нового события при нажатии на чекбокс
Добавил возможность настраивать Expand и Fill параметры чекбоксов

Различные изменения в EnumCheckList

---

QS.Project/Project.DB/CustomProjections.cs

Почистил код, заменил пробелы на табы

Добавил проекцию Concat

---

QS.Report/QS.Report.csproj

Добавил пакет System.Drawing.Common в QS.Report

Фикс сборки QS.Report

---

QS.Report.Gtk/Views/SelectablePrintersView.cs
QS.Report/IReportPrinter.cs
QS.Report/QS.Report.csproj
QS.Report/Repository/IUserPrintingRepository.cs
QS.Report/Repository/UserPrintingRepository.cs
QS.Report/ViewModels/SelectablePrintersViewModel.cs
QSReport/DefaultPrintOperation.cs
QSReport/MultiplePrintOperation.cs
QSReport/QSReport.csproj
QSReport/ReportPrinter.cs

Различные доработки и улучшения, свазанные с печатью отчётов

Обновлён класс печати отчётов (ReportPrinter). Добавлена поддержка MultiplePrintOperation

---

QSReport/MultiplePrintOperation.cs

Сделал некоторые функции статическими
Добавил проверку на уже запущенную печать

Убрал многопоточность из MultiplePrintOperation

---

QS.BaseParameters/ParametersService.cs

Немного изменена логика загрузки параметров, теперь обращение к базе идет не в момент создания класса, а при первом обращении к списку параметров. По сути реализована лейзи загрузка.
Может убрать лишние обращения к базе, так где класс с параметрами создан, но не был использован.

Добавлен асинхронный метод для загрузки параметров.

---

QS.Testing/Deletion.Testing/DeleteConfigTestBase.cs
QS.Testing/HistoryLog.Testing/DomainModelTestBase.cs
QS.Testing/QS.Testing.csproj
QS.Testing/ViewModels/EntityViewModelsTestsBase.cs

- Добавлена возможность проверять, у всех ли отслеживаемых свойств установлено русское название.
- Добавлена возможность проверять наличие родительского падежа, для корректного отображения названия диалога.
- Мелкие правки, в основном орфография.

Добавлены методы тестирования для отслеживания изменний

---

QS.LibsTest.Core/Updater/UpdateConfigurationTests.cs
QS.Testing/QS.Testing.csproj
QS.Testing/Updater.Testing/DbConfigurationTestBase.cs
QS.Updater.Core/DB/UpdateConfiguration.cs
QS.Updater.Gtk/DB.Views/UpdateProcessView.cs
QS.Updater.Gtk/gtk-gui/QS.Updater.DB.Views.UpdateProcessView.cs
QS.Updater.Gtk/gtk-gui/gui.stetic
QS.Updater/DB/SQLDBUpdater.cs
QS.Updater/DB/ViewModels/UpdateProcessViewModel.cs

Добавлены тесты корректной последовательности обновлений.

Удалена функциональность микро обновлений

---

Binding/Gamma.Binding/GtkWidgets/yTreeView.cs

Поменял проверку, т.к. идут проблемы, когда в тривьюхе больше одной строки

Фикс тривьюхи

---

QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs

Убираем присвоение null Completion, чтобы не летела ошибка NullRef в OnListUpdated

Фикс NullRefException в EntityViewModelEntry

---

QS.Osrm/OsrmClient.cs

1.  построение маршрута без учета платных дорог

Исключаем платные дороги

---

QS.Project.Gtk/Tdi/TdiNotebook.cs

если было множество кликов на кнопку закрытия

Исправление вылета приложения при закрытии вкладки

---

QS.Project.Core/DomainModel/Tracking/UowWatcher.cs

Также логируем SessionId, чтобы быстрее найти незакрытые uow

Поменял ключ в словаре на гуид и теперь отслеживаем uow по SessionId

---

QSOrmProject/RepresentationModel/RepresentationModelBase.cs
QSOrmProject/RepresentationModel/RepresentationModelEntityBase.cs

переделал доступность некоторых полей/свойств/методов для доступа и переопределения их в потомках

Обновление RepresentationModelBase

---

QS.Project/Project.Journal/FilterableSingleEntityJournalViewModelBase.cs
QS.Project/Project.Journal/SingleEntityJournalViewModelBase.cs

В классах SingleEntityJournalIViewModelBase  и FilterableSingleEntityJournalIViewModelBase в вызов конструктора базового класса добавлен параметр NavigationManager

В вызов базового класса добавлен NavigationManager

---

QS.Project/ViewModels/Control/EEVM/CommonEEVMBuilder.cs
QS.Project/ViewModels/Control/EEVM/JournalViewModelAutocompleteSelector.cs
QS.Project/ViewModels/Control/EEVM/JournalViewModelSelector.cs

Добавление параметров фильтра для EntityEntry

Добавление параметров фильтра для EntityEntry

---

Binding/Gamma.Binding/Gamma.Binding.csproj
Binding/Gamma.Binding/GtkWidgets/ySpinButtonCurrencyFormat.cs
Binding/Gamma.Binding/gtk-gui/objects.xml

Значение отображается с пробелом между разрядами и двумя знаками после запятой

Добавлен yspinbutton с денежным форматом отображения

---

QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs

открываем один журнал для поиска и освобождаем память при пересоздании списка для Completion

Правка EntityViewModelEntry

---

QS.HistoryLog.Gtk/Views/HistoryView.cs

Resizable колонок в журнале изменений

---

QS.HistoryLog/Domain/FieldChange.cs
QS.HistoryLog/HibernateTracker.cs
QS.HistoryLog/HistoryAttributes.cs

Добавлен механизм трекинга для связи сущностей по Id, без связи напрямую через свойство.

Добавлен механизм трекинга

---

QS.Project/ViewModels/EntityTabViewModelBase.cs

Не работал с разнотипными полями

Фикс подписки на изменения поля сущности

---

QS.Project.Core/DomainModel/Entity/PropertyChangedBase.cs

Если приходит Unary, нужна другая обработка

Фикс определения имени свойства

---

QS.Project.Gtk/Views/Control/EntityEntry.cs

Отписка от события
Фикс приходящего события, при уже уничтоженном экземпляре автозагрузчика

Фикс EntityEntry

---

QS.Project.Core/DomainModel/Entity/AppellativeAttribute.cs

Исправлена невозможность назначения AppellativeAttribute для enum

Хотфикс - AppellativeAttribute

---

QS.Project.Core/DomainModel/Entity/IArchivable.cs
QS.Project.Core/DomainModel/Entity/INamed.cs
QS.Project.Core/DomainModel/Entity/INamedDomainObject.cs
QS.Project.Core/DomainModel/Entity/ITitled.cs

- IArchivable
- INamed
- ITitled

Интерфейсы

---

Binding/Gamma.Binding/TreeModels/RecursiveTreeModel.cs

Вылетало при подключении пустого списка с ошибкой дескриптор не инициализирован

Фикс биндинга пустого списка

---

QS.Project.Gtk/Widgets.GtkUI/VehicleRegistrationNumberEntry.cs

Исправлен стандартный цвет в виджете
Стандартный цвет не является черным.

Хотфикс - цвет

---

QS.Project.Gtk/Widgets.GtkUI/VehicleRegistrationNumberEntry.cs

Исправлен цвет (для мастера)
Черный не является стандартным

Хотфикс - цвет Entry

---

QS.Project.Core/Deletion/Configuration/DeleteConfiguration.cs
QS.Project.Core/Deletion/Configuration/DeleteInfo.cs
QS.Project.Core/Deletion/Configuration/DeleteInfoHibernate.cs
QS.Project.Core/Deletion/Configuration/IDeleteInfo.cs
QS.Project.Core/Deletion/Configuration/UpdateDependenceInfo.cs
QS.Project.Core/Deletion/DeleteCore.cs
QS.Project.Core/Deletion/Operations.cs

Добавлено действие обновления при удалении

Расширение конфигурации удаления

---

QS.Project.Core/Deletion/Configuration/DeleteConfiguration.cs
QS.Project.Core/Deletion/Configuration/DeleteInfo.cs
QS.Project.Core/Deletion/Configuration/DeleteInfoHibernate.cs
QS.Project.Core/Deletion/Configuration/IDeleteInfo.cs
QS.Project.Core/Deletion/Configuration/UpdateDependenceInfo.cs
QS.Project.Core/Deletion/DeleteCore.cs
QS.Project.Core/Deletion/Operations.cs

Добавлено действие обновления при удалении

Обновление при удалении (мастер)

---

QS.Project.Gtk/Tdi/TdiNotebook.cs

Добавлены функции закрытия множества вкладок
- Закрыть
- Закрыть остальные
- Закрыть справа
- Закрыть слева (кроме текущей группы (исключая окна текущей вложенности))
Добавлена функция закрытия на среднюю кнопку мыши

Контекстное меню для заголовков табов

---

QS.Project.Gtk/Tdi/TdiNotebook.cs

Закрытие других вкладок как в браузере и закрытие по средней кнопке (копия ПР для мастера)

Меню для табов

---

QS.Project.Gtk/Views/Control/EntityEntry.cs
QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs

Добавлено выделение цветом текста и тултип, если введён текст, но не выбрана сущность.

Выделение текста цветом и тултип

---

QS.Project.Desktop/Navigation/NavigationManagerBase.cs
QS.Project.Gtk/Navigation/TdiNavigationManager.cs

Открыл методы для перезаписи потомками

Фикс NavigationManager

---

QS.Project.Core/DomainModel/Tracking/GlobalUowEventsTracker.cs

1. Исправление ошибки, когда в двух последовательных транзакциях меняется одна и та же сущность.
2. Открыт OnPostCommit для отслеживания изменений своих транзакций. Раньше он вызывался только внутри UoW.Commit()), но иногда нужно коммитить свою транзакцию вне UoW.Commit() и далее вызывать трекер, например:
using (var transaction = UoW.Session.BeginTransaction())
{
UoW.Session.Save(...);
transaction .Commit();
GlobalUowEventsTracker.OnPostCommit((IUnitOfWorkTracked)UoW);
}

Отслеживание изменений при коммите транзакции

---

QS.Project.Gtk/Journal.GtkUI/JournalView.cs
QS.Project/Project.Journal/JournalViewModelBase.cs

Добавлена настройка для журналов - раскрывать дерево после перезагрузки элементов

Разворачивание дерева (настройка журнала)

---

QS.Project.Core/DomainModel/Entity/PropertyChangedBase.cs

This reverts commit 25c15e27ac8c22e708aef422acac0c56ed66bccd.
Вызвало много проблем

Revert "Фикс оповещений по цепочке"

---

QS.Project.Core/DomainModel/Entity/PropertyChangedBase.cs

Возврат ограничения цепочки оповещений

---

QS.Project.Core/DomainModel/Entity/PropertyChangedBase.cs

Для возможности совместного использования его в ReactiveUI

Доработки PropertyChangedBase 

---

QS.Project/Project.Journal/DataLoader/ThreadDataLoader.cs
QS.Project/Project.Journal/JournalViewModelBase.cs

- убран сброс последней позиции AnyDataLoader
- фикс скролла в случаях, когда загружено элементов меньше размера страницы, но уже появился скролл

Доработка AnyDataLoader и фикс скролла

---

QS.HistoryLog/HibernateTracker.cs

если изменений много, бьем на несколько частей, чтобы не превышать размер передаваемого пакета

обновление записи истории изменений

---

QS.Features/Serial/Encoding/SerialNumberEncoder.cs
QS.Features/Serial/ViewModels/SerialNumberViewModel.cs
QS.Project.Desktop/Project.Versioning/Product/IProductService.cs
QS.Project/Project.ViewModels/AboutViewModel.cs

Также добавлен метод для получения названия редакции по её id

Добавлена дата истечения срока действия серийного номера

---

QS.Project.Gtk/Tdi/TdiNotebook.cs
QS.Project/Tdi/ICustomCancellationConfirmation.cs
QS.Project/Tdi/IHasChanges.cs
QS.Project/Tdi/ISaveable.cs
QS.Project/Tdi/ITdiDialog.cs

Разбиты интерфейсы
Скорректированы вызовы сохранения

Исправление проверки необходимости сохранения для новых диалогов

---

QS.Project.Gtk/Tdi/TdiNotebook.cs
QS.Project/Tdi/ICustomCancellationConfirmation.cs
QS.Project/Tdi/IHasChanges.cs
QS.Project/Tdi/ISaveable.cs
QS.Project/Tdi/ITdiDialog.cs
QSOrmProject/QSOrmProject.csproj
QSOrmProject/ViewModels/Control/EEVM/LegacyDlgOpener.cs
QSOrmProject/ViewModels/Control/EEVM/LegacyEEVMBuilder.cs

Исправлено поведение кнопки отмены при необходимости сохранения

Изменение функционала кнопки отмены

---

Modules/QSDocTemplates/OdtWorks.cs

Тот же самый хотфикс OdtWorks, ждет принятия ПР в мастер

Исправлен косяк проверки имени поля в документе (ветка pacs)

---

QS.Report/QS.Report.csproj

Мешает компиляции из-за зависимости

Qs.Report переведен на netstandard2

---

QSSaaS/QSSaaS.csproj
QSScan/QSScan.csproj

Еще 2 проекта с неактуальной версией

Обновление проектов до 462

---

QS.Project.Core/Commands/AsyncCommand.cs

Исправление бага с обращением в защищенную память

Исправление AsyncCommand

---

QS.Project.Desktop/Commands/AsyncCommand.cs

Была обнаружена проблема с рассинхронизацией потоков

Исправление работы AsyncCommand

---

QS.Project.Gtk/Widgets.GtkUI/UserEntityPermissionWidget.cs
QS.Project/Project.Repositories/TypeOfEntityRepository.cs
QS.Utilities/Extensions/IListExtensions.cs

- исправил удаление права сотрудника;
- немного отрефакторил

Правка виджета прав на документы по сотруднику

---

QS.Project.Core/DomainModel/Tracking/UowWatcher.cs
QS.Project/Project.Filter/FilterViewModelBase.cs

добавил к выводу инфы о uow его Title
в Title вью модели фильтра добавил имя класса для удобного поиска

изменения для отслеживания утечек соединений

---

Binding/Gamma.Binding/Widgets/SidePanels/LeftSidePanel.cs
QS.Project.Gtk/Journal.GtkUI/JournalView.cs
QS.Project.Gtk/Tdi/TabVBox.cs
QS.Project.Gtk/Tdi/TdiNotebook.cs
QS.Project.Gtk/Widgets.GtkUI/DatePicker.cs
QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
QS.Report.Gtk/Views/RdlViewerView.cs
QS.Report/ViewModels/RdlViewerViewModel.cs

очередная порция изменений для устранения утечек

устранение утечек

---

Modules/QS.Banks/Domain/Account.cs
QS.Project/ViewModels/Control/EEVM/JournalViewModelSelector.cs

Исправлено открытие журнала
Изменен заголовок у Account

Правки в открытии журнала и замена заголовка аккаунта (master)

---

QS.Project/ViewModels/Control/EEVM/EntityEntryViewModel.cs

Например при удалении ответственного, если ведомость уже создана.

Добавила свойство для возможности заблокировать удаление.
