- QS.LibsTest/NLog.config
- QS.LibsTest/QS.LibsTest.csproj
Сомневаюсь насколько это надо. Но вот понадобилось один раз, вдруг все поддержат и оставим.
Добавлен конфиг Nlog-а в проект с тестами, чтобы во время тестов все что падает из классов в Nlog, отправлялось во первых на консоль при запуске на машине разработчика, во вторых в дженкинсе отображалось в общем логе сборки. В некоторых сложных ситуациях, позволяет быстрее понять что же не так происходило при выполнении упавшего теста.
У меня нет уверенности что это удобно выводить именно в консоль на дженкинсе.
> В при выполнении тестов пишем логи в консоль.

- QS.Project/Project.Journal/JournalViewModelBase.cs
Эта строчка немного путает, так как создается впечатление что в момент установки свойства вызовется метод CreateNodeActions, в реальности он никогда не вызовется так как свойство и так в None. А так как оно все равно в None. Здесь установка его безсмыслена. Изменение не на что не влияет, просто может кто-то другой не запутается, так же как я.
> Просто лишняя строчка.

- Modules/CustomFields/QSCustomFields.csproj
- Modules/CustomFields/packages.config
- Modules/QSAttachment/QSAttachment.csproj
- Modules/QSAttachment/packages.config
- QS.HistoryLog.Gtk/packages.config
- QS.LibsTest/QS.LibsTest.csproj
- QS.LibsTest/packages.config
- QS.Project.Gtk/QS.Project.Gtk.csproj
- QS.Project.Gtk/packages.config
- QS.Project/QS.Project.csproj
- QS.Project/packages.config
- QS.Updater.Gtk/QS.Updater.Gtk.csproj
- QS.Updater.Gtk/packages.config
- QSOrmProject/QSOrmProject.csproj
- QSOrmProject/packages.config
- QSOsmBaseScripts/QSOsmBaseScripts.csproj
- QSOsmBaseScripts/packages.config
- QSOsmService/QSOsmService.csproj
- QSOsmService/packages.config
- QSProjectsLib/QSProjectsLib.csproj
- QSProjectsLib/packages.config
- QSSupportLib/QSSupportLib.csproj
- QSSupportLib/packages.config
Для проекта QSOsmBaseScripts пришлось поднять минимальную платформу до 4.6.1 из-за библиотеки Npgsql
> Обновление пакетов  Nuget

- QS.Project.Gtk/Project.Search.GtkUI/SearchView.cs
Ребята, давайте все таки по умолчанию будет задержка поиска нулевая.
Все таки водовоз это один проект. В котором будет стоять эта задержка. Иначе получается мне надо будет во всех проектах проставлять эту настройку в 0. Лучше мне кажется в одном проекте проставить такую настройку.
Во вторых, ваши пользователи видимо привыкли уже к этой задержке, мои нет. У меня во всех проектах еще старые журналы Representation, где нет таких больших задержек и фильтрация списков особенно простых справочников с меньшей чем 1000 количества элементов, происходит моментально. При внедрении новых журналов вместо старых, создается реальное впечатление что поиск тормозит, даже при 10 элементах в списке, в новых справочниках, по сравнению с другими которые не переведены еще.
P.S. для Вадима. Мне кажется что …
> Установка нулевой задержки в поиске.

- QS.Project/Project.DB/Connection.cs
- QS.Updater.Gtk/DBUpdater/DBUpdater.cs
- QS.Updater.Gtk/DBUpdater/SQLDBUpdater.cs
- QSOrmProject/OrmMain.cs
Во первых проблема возникает у проектов не использующих OrmProject, и линковать на него ради заполнения этого поля. нет.
Во вторых апдейтер все равно надо переделывать и отлинковывать его древней QSPojectsLib. А так как она слинкована уже пускай билдер сама возьмет
В третьи надо отказываться от статических настроек по максимуму. Поэтому так эта настройка все равно в будущем не нужна.
> Переделал передачу билдера в апдейтер.

- QS.Project.Gtk/QS.Project.Gtk.csproj
Изначально предполагалось что будет вот такая схема.
QS.ModleName.Name - Код не связанный с UI
QS.ModleName.Name.GtkUI - Код UI
QS.ModleName.Name.WpfUI - Код UI
То есть, код каждого модуля лежит в аналогичном названии пространства имен, но с припиской вида интерфейса.  Вроде выглядит красиво, НО:
- Выбор нейспеса в автодополнии, зашел в "папку", а там тебе на выбор неймспейсы с разными GUI, собственно ради чего вся эта красота затевалась, не будет работать. Так как навряд ли будут проекты или библиотеки которые будут одновременно линковать несколько GUI и поэтому не имеет смысла держать неймспейсы как бы рядом.
- Концепция добавления GUI в конец не позволяет из имен папок делать иерархию, подпапок. Например QS.Views.GtkUI и QS.Views.Control.GtkUI уже не объединить иерархически в папки …
> Решил поменять концепцию наименования пространства имен для UI

- QS.Project/DomainModel/Entity/DomainHelper.cs
Чтобы их по возможности не использовали и в будущем выпилили.
Считаю было не правильное решение запихать эти методы сюда. Нужно было, делать копию DialogHelper или что нибудь в этом роде. К доменной модели они мало имеют отношения. Что доказывать тот факт что в новых Диалогах они не нужны, а методы работы с доменной моделью нужны.
Сейчас переделывать уже слишком много, поэтому просто пометим как устаревшие.
> Пометил методы в классе DomainHelper как устаревшие.

- QS.Project.Gtk/Widgets.GtkUI/DatePicker.cs
- QS.Project.Gtk/Widgets.GtkUI/DateRangePicker.cs
После нескольких успешных билдов, почему начал падать виджет выбора одиночной даты. Поэтому переделано на установку ширины всего диалога вместо внутреннего виджета
> Переделана установка ширины выбора даты с внутреннего виджета на сам диалог

- QS.Project/DomainModel/UoW/UnitOfWorkBase.cs
- QS.Project/DomainModel/UoW/UnitOfWorkChild.cs
UnitOfWorkChild должен использовать транзакцию из parentUoW. Для этого ему нужно дать использовать OpenTransaction из parentUoW. В будущем необходимо полностью отказаться от изпользования Child
> Исправил ошибку с транзакцией в UnitOfWorkChild

- QS.Project.Gtk/Navigation/GtkWindowsNavigationManager.cs
- QS.Project/Project.Journal/EntityJournalViewModelBase.cs
- При открытии диалога не вызываем Run и вообще работает без него. Так как он загодняет программу в локальный цикл ожидания ответа диалога. А у нас там ViewModel которые расчитаны на другую работу.
- Соответсвено реализовано более корректное закрытие окон.
- Исправлена проблема с обновление заголовка окна.
> Исправлена работа Менеджера навигации на обычных диалогах Gtk

- QSProjectsLib/Login.cs
Это поле в некоторых проектах используется для отображения названия базы в заголовке программы.
При этом получалось что там всегда отображается только название которое было при старте.
> Исправлено заполнение поля SelectedConnection при переключении базы 

- QS.Project.Gtk/RepresentationModel.GtkUI/IRepresentationModel.cs
Он дублирует аналогичный в из OrmProject. И я уже задолбался ловить ошибки в AutoFac, потому видимо подключаю пространства имен на автомате, первое что попалось, и постоянно выбирается не тот интерфейс.
При этом он реально используется только в части диалогов водовоза. И думаю должен быть удален в будущем.
> Пометил интерфейс как устаревший.

- QS.Testing/Deletion.Testing/DeleteConfigTestBase.cs
Они должны удаляться обратной ссылкой.
> При проверке удаления игнорируем обратные связи OneToOne

- QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
- QS.Project/Project.Journal/EntityJournalViewModelBase.cs
- QS.Project/Project.Journal/JournalViewModelBase.cs
Он нужен во всех журналах, даже реализованных на JournalViewModelBase при этом в текущей реализации его все равно ни на что другое не заменить.
> Поиск в журнале перенесен в базовый класс журнала.

- QS.Project.Gtk/Dialog.GtkUI/DialogHelper.cs
- QS.Project.Gtk/Dialog.GtkUI/IFilterWidgetResolver.cs
- QS.Project.Gtk/Journal.GtkUI/JournalView.cs
- QS.Project.Gtk/Project.Dialogs.GtkUI/RepresentationJournalDialog.cs
- QS.Project/DomainModel/Entity/PropertyChangedBase.cs
- QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
- QS.Project/Project.Journal/IJournalFilterViewModel.cs
- QS.Project/Project.Journal/JournalFilterViewModelBase.cs
- QS.Project/Project.Journal/JournalViewModelBase.cs
- QS.Project/QS.Project.csproj
В этой реализации:
- Упростил интерфейс фильтра. По сути он как таковой особо и не нужен. Оставил только свойство для автоскрытия фильтра. Так как фильтр для журнала, он сам может вызвать метод рефреш журнала. События и подписки в данной схеме усложняют код.
- Убрал из фильтра лишние методы, и изменил логику, на практике не вижу особой необходимости иметь в модели фильтра свойства с уведомлением об обновлении, но при этом не обновляющие сам фильтр. Поэтому логичнее чтобы по умолчанию все свойства вызывающие проперти чендж, вызывали обновления фильтра. И уж если вдруг понадобится, можно сделать исключения для каких нибудь. Это позволяет писать меньше кода, и не описывать дополнительно все свойства которые изменяют фильтр.
- Из основного журнала выпили старый интерфейс фильтра и оставил его …
> Реализовал другой вариант фильтра для журнала. 

- QS.Project/DomainModel/UoW/NhibernateExtend.cs
- QS.Project/DomainModel/UoW/UnitOfWork.cs
- QS.Project/DomainModel/UoW/UnitOfWorkWithoutRoot.cs
- QS.Project/QS.Project.csproj
Есть давно известный баг https://github.com/nhibernate/nhibernate-core/issues/1413 в том что при вызове IsDirty хибернейт может сохранять изменения в базу. Частично это решается открытием транзакции. которая откатывается при отмене. Но если какие то из полей стоят not-null то проблема записи при проверке не исчезает. Поэтому реализована собственная проверка на изменения. Откуда взять код указано в начале класса.
> Добавлен обходной путь проблемы с проверкой изменений через IsDirty

- QS.LibsTest/Navigation/TdiNavigationManagerTest.cs
- QS.Project.Gtk/Navigation/TdiNavigationManager.cs
Если мастер вкладка была null, то в списке страниц создавалась пустая страница, без вкладки.
> Исправлен баг найденный тестом.

- QS.HistoryLog.Gtk/QS.HistoryLog.Gtk.csproj
- QS.HistoryLog.Gtk/packages.config
Из-за не совместимости с пакетом Microsoft.NETFramework.ReferenceAssemblies.net461.
Обновление DiffPlex в библиотеке требует обновления до той же версии и в проекте водовоза.
А при обновлении версии DiffPlex добавляет зависимый пакет Microsoft.NETFramework.ReferenceAssemblies.net461. Он в свою очередь ломает сборку водовоза. После его добавления ни в одном файле не получается найти классы или пространство имен в пространстве имен Vodovoz. Например не может найти Domain namespace в Vodovoz.
Причину пока не удалось выяснить. Предлагаю если это возможно, пока откатить обновление этого пакета.
> Откат обновления пакета DiffPlex

- QS.Project/ViewModels/Control/EEVM/EntityEntryViewModel.cs
Само событие сделано так что, оно не требует аргументов.
При этом EntitySelectedEventArgs не позволяет получать null в качестве entity. Поэтому мы падаем при попытке очистить поле.
> Исправил вызов события изменения.

- QS.Project.Gtk/Views/Control/EntityEntry.cs
- QS.Project/QS.Project.csproj
- QS.Project/ViewModels/Control/EEVM/CommonEEVMBuilder.cs
- QS.Project/ViewModels/Control/EEVM/EntityEntryViewModel.cs
- QS.Project/ViewModels/Control/EEVM/FuncEntityAdapter.cs
- QS.Project/ViewModels/Control/EEVM/IEntityAdapter.cs
- QS.Project/ViewModels/Control/EEVM/IEntityAutocompleteSelector.cs
- QS.Project/ViewModels/Control/EEVM/IEntityEntryViewModel.cs
- QS.Project/ViewModels/Control/EEVM/IEntitySelector.cs
- QS.Project/ViewModels/Control/EEVM/JournalViewModelAutocompleteSelector.cs
- QS.Project/ViewModels/Control/EEVM/JournalViewModelSelector.cs
- QS.Project/ViewModels/Control/EEVM/UowEntityAdapter.cs
- QS.Project/ViewModels/Control/ESVM/EntitySearchViewModel.cs
- QSOrmProject/ViewModels/Control/EEVM/OrmReferenceAutocompleteSelector.cs
- QSOrmProject/ViewModels/Control/EEVM/OrmReferenceSelector.cs
Так же добавил возможность заменить эту функциональность на метод.
Нужно для того чтобы можно было наладить нормальную работу контролов выбора сущностей с журналами которые не работают через uow и как следствие не имеют сохранного в базе объекта который можно загрузить через uow имеющимися средствами. Но есть возможность заполнить эту сущность данными из другой системы.
> Вынес функциональность связанную с загрузкой сущьности в отдельный класс

- QS.Project.Gtk/Project.Search.GtkUI/OneEntrySearchView.cs
Очень странный баг при закрытии журнала на винде вызывалось исключение  GLib.MissingIntPtrCtorException: GLib.Object subclass при в момент перебора всех дочерних виджетов. На линуксе такого не происходило. Пробовал разные варианты обойти проблему. Похоже добавление постых конструкторов самый адекватный вариант.
> Исправление бага с закрытием журналов.

- QS.Project.Gtk/Journal.GtkUI/JournalView.cs
Раньше PopupActions с параметром Visibility = false были видны.
> Исправлена отрисовка PopupActions с параметром Visibility.

- QS.Project/Deletion/Configuration/DeleteConfiguration.cs
- QS.Project/Deletion/Configuration/DeleteInfoHibernate.cs
- QS.Project/Deletion/DeleteConfig.cs
- QS.Project/DomainModel/UoW/IUnitOfWork.cs
- QSOrmProject/OrmReference.cs
- QSOrmProject/ReferenceBase.cs
Иногда происходит нарушение ключенй например всем ссылкам в объекте проставился id=0 или что-то другое. Такие объекты до этого нельзя было удалить, так как механизм падал при попытке проверить ссылку на объект с id=0 которого нет в базе. В данном случае мы перехватываем экспешен что объекта нет. И просто не пытаемся его дальше проверять эту ветку, это просто неверная зависимость.
> Не падаем при удалении обектов в базе, в которых есть поломанные ссылки

- QS.Project/Deletion/Configuration/DeleteInfoHibernate.cs
- QS.Project/Deletion/Operations.cs
Оно позволяло не падать при проверке ссылок, но все равно падало при удалении.. Здесь исправление.
+ id удаляемого объекта тоже заносим в лог, для более удобного дебага.
> Предыдущее исправление удаления битых ссылок, было не полным.

- QS.Project/DomainModel/Entity/PropertyChangedBase.cs
Понимаю что это не совсем здоровая ситуация. И по идеи обновление должно вызываться именно для реального свойства. Но в некоторых ситуациях хочеться сделать аля виртуальное свойство именно для уведомления. Например сослаться на какое то поле второго уровня в нутри класса. И так как имея передается в виде строки, то это работает. И для получения таких уведомлений реального свойства не требуется.
> Не падаем если уведомление вызывается для свойства которое отсутствует у класса.

- QS.Project.Gtk/Navigation/TdiNavigationManager.cs
Предполагаю что точно не учитывается положение панели в низу и бортиков окна. Так как не понятно как правильно учесть. Реализован обходной путь.
> Обход некорректного расчета положения окна на виндовс

- QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
- QS.Project.Gtk/gtk-gui/QS.Widgets.GtkUI.EntityViewModelEntry.cs
- QS.Project.Gtk/gtk-gui/gui.stetic
Сейчас одно нажатие backspase в EntityViewModelEntry стирает имя целиком, что неудобно.
> Не стирать имя целиком

- QS.Project.Gtk/Tdi/TdiNotebook.cs
Чтобы не возникало ситуации когда пользователь не может закрыть вкладку, потому что при вопросе о необходимости закрытия или при проверках внутри диалога могли возникнуть ошибки.
> Закрываем вкладку если при проверку закрытия возникла ошибка

- QS.Utilities/Properties/AssemblyInfo.cs
- QS.Utilities/QS.Utilities.dotnet.csproj
Потихоньку начинаем переводить библиотеки на работу под dot net Core. Пока опыт проекта манго для Водовоза показывает что проще всего создавать отдельный Солющен и проджек файл. потому что окружение как правило разно, и используются разные версии библиотек, при этом сам код обычно такой же. Если научимся нормально работать с мулти таргетом, можно начать делать по другому.
> Добавлен проект библиотеки под dotnet

- QS.Project.Gtk/Navigation/GtkWindowsNavigationManager.cs
- QS.Project.Gtk/Navigation/TdiNavigationManager.cs
До этого при сворачивании дополнительного окна на винде так же сорачивалось и основное оно программы. что выглядит странно в тех случаях когда окно не модальное.
> Исправляем баг со сворачиванием окна на виндовс

- Modules/CustomFields/QSCustomFields.csproj
- Modules/CustomFields/packages.config
- Modules/QSAttachment/QSAttachment.csproj
- Modules/QSAttachment/packages.config
- QS.Project.Gtk/QS.Project.Gtk.csproj
- QS.Project.Gtk/packages.config
- QS.Project/QS.Project.csproj
- QS.Project/packages.config
- QS.Updater.Gtk/QS.Updater.Gtk.csproj
- QS.Updater.Gtk/packages.config
- QSOrmProject/QSOrmProject.csproj
- QSOrmProject/packages.config
- QSProjectsLib/QSProjectsLib.csproj
- QSProjectsLib/packages.config
- QSSupportLib/QSSupportLib.csproj
- QSSupportLib/packages.config
При чтении таких полей внутри Mysql.Data не правильно проверяется длина и падает при невозможности использования значения длины -1.
> Откат Mysql.Data до версии 8.0.19 из-за ошибки в новой версии в работе с Nullable GUID полями.

- QS.Project.Gtk/Dialog.GtkUI/GtkQuestionDialogsInteractive.cs
- QS.Project.Gtk/Dialog.GtkUI/MessageDialogHelper.cs
Это лучше чем просто название экзешника, в случае если программист не позаботился об указании специфичного текста.
> Заполняем заголовки диалогов текстом по умолчанию.

- QS.Project.Gtk/Tdi/TdiNotebook.cs
Очень грязный хак, который необходим для очистки памяти при закрытии вкладки. Однако без него не получится очистить память после отчётов как на приложенном графике.
> Adds GCCollect to clean memory after reports

- QS.Project/DomainModel/Entity/DomainHelper.cs
так как этот метод обычно используется для отображения информации об объекте, обычно в этом месте мы просто хотим вывести инфу и не упасть. Это может избавить от лишней проверки на null перед вызовом метода.
> Думаю будет универсальнее не падать если объект null, а возвращать null

- QS.MachineConfig/Configuration/IChangeableConfiguration.cs
- QS.MachineConfig/Configuration/IniFileConfiguration.cs
- QS.MachineConfig/DefaultMachineConfig.cs
- QS.MachineConfig/IMachineConfig.cs
- QS.MachineConfig/MachineConfig.cs
- QS.MachineConfig/QS.MachineConfig.csproj
Пока интерфейс имеет только базовую, но рабочую реализацию.
У меня нет 100% уверенности в правильность этого решения. Вообще в идеале хотелось бы перейти на конфигурации от MS IConfiguration, которая во всю используется в net. Core и доступна из нугет пакетов во фреймворке. НО она работает только на чтение. То есть изменять значения там нельзя. А при нашем использовании это очень часто надо. Но при этом в новой конфигурации все таки хочется попробовать реализовать интерфейс асбтрагированный от конкретного места хранения (ini file) и отвязанный от nini. В текущем интерфейсе IMachineConfig работа происходит напрямую с Nini. Это возможно вызовет проблемы при переводе библиотек на Core, так как по-моему в Nini не развивается совсем. Есть какой то пакет Nini в названии для нет стандарта, но на …
> Предложен первоначальный вариант нового интерфейса обращения к конфигурации в Ini файле

- QS.Project.Gtk/Widgets.GtkUI/TimeEntry.cs
Только если такая запись просходит автоматически
> Убрал назойливый звук из TimeEntry, возникающий когда в Entry записывается больше символов чем MaxLength

- QS.Project/Deletion/ViewModels/DeletionProcessViewModel.cs
Если в момент удаления . Произошла ошибка, то при нажании за закрытие окна или кнопку отмена, вызывался эксепшен, что токен уже уничтожен. Так как проверить это нельзя. перехватываем эксепшен.
> Не падаем там где можем не падать.

- QSOrmProject/OrmReference.cs
Из-за того что созданные в журнале uow не закрывался после закрытия вкладки могла утекать память. И могли приходить уведомления об изменение объекта для уже закрытого журнала.
> Исправлены ошибки и утечки

- QS.Project.Gtk/Tdi/TdiNotebook.cs
В этом методе при выборе пользователем нет, виджет вкладки разрушался сразу же. Хотя вызвавший метод, все равно бы закрыл вкладку при ответе true. А так как вкладка разрушалась раньше. Нормального закрытия не происходило. Так как не вызывались правильно дестрои для внутренних виджетов в этой строке https://github.com/QualitySolution/QSProjects/blob/master/QS.Project.Gtk/Tdi/TdiNotebook.cs#L430 Из-за за этого могла быть утечка памяти в виджетах и так как виджет продолжал висеть в памяти. И происходили ошибки в обработке глобальных событий. На уже закрытых вкладках.
> Исправлена утечка виджетов.

- QS.Project/Project.Journal/JournalAction.cs
Так как в случае создания дочерних действий, приходится создавать пустую лямбду, что выглядит по дурацки.
> Дана возможность не указывать функцию для действия

- QS.Project/Project.Journal/DataLoader/DynamicQueryLoader.cs
- QS.Project/Project.Journal/DataLoader/ThreadDataLoader.cs
Иногда бывают ситуация при которых запрос подсчитывает неправильное количество сторок, так как группировка данных пропадает, в таких запросах. Поэтому добавлена возможность, добавлять при формировании запроса, учитывать место его использования, и модифицировать для подсчета строк. Детали описал в документации https://github.com/QualitySolution/QSProjects/wiki/%D0%94%D0%B8%D0%B0%D0%BB%D0%BE%D0%B3%D0%B8-%D0%B6%D1%83%D1%80%D0%BD%D0%B0%D0%BB%D0%BE%D0%B2#%D0%9F%D0%BE%D0%B4%D1%81%D1%87%D0%B5%D1%82-%D0%BE%D0%B1%D1%89%D0%B5%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B0-%D1%81%D1%82%D1%80%D0%BE%D0%BA
> Добавлена возможность модифицировать запрос при подсчете строк

- QS.LibsTest/ViewModels/Dialog/EntityDialogViewModelBaseTest.cs
- QS.Project/QS.Project.csproj
- QS.Project/Validation/IValidator.cs
- QS.Project/Validation/ObjectValidator.cs
- QS.Project/Validation/ValidationRequest.cs
- QS.Project/ViewModels/Dialog/EntityDialogViewModelBase.cs
- QS.Project/ViewModels/Dialog/UowDialogViewModelBase.cs
Во ViewModel теперь можно добавить проверку не только основного объекта диалога, но и другие объекты, в том числе и саму ViewModel для проверки свойств напрямую не сохраняемых в БД.
> Валидатор теперь может проверять несколько объектов

- QS.Project/DomainModel/Entity/DomainHelper.cs
Собирает список Id из любой коллекции(IEnumerable).
По сути у каждого элемента коллекции вызывает метод GetId, со всеми вытекающими:
- он упадет при отсутствии поля Id, у элемента
- порядок и количество элементов будет идентичное, оригинальному перечислению
- если в коллекции будут элементы с дубликатами id, в результатах дубликаты тоже будут
> Добавлен метод GetIds в DomainHelper

- QS.Project.Gtk/Journal.GtkUI/JournalView.cs
- QS.Project.Gtk/Navigation/GtkWindowsNavigationManager.cs
- QS.Project.Gtk/Navigation/TdiNavigationManager.cs
- QS.Project/QS.Project.csproj
- QS.Project/ViewModels/Dialog/WindowDialogViewModelBase.cs
- QS.Project/ViewModels/Extension/IWindowDialogSettings.cs
Предыдущая реализация не открывала обычные viewModel например журналы. Не знаю как получилось, что завязались на дочерний класс.
> Переделал GtkWindowsNavigationManager для того чтобы работали обычный view модели.

- QS.Updater/DB/SQLDBUpdater.cs
- QS.Updater/DB/ViewModels/UpdateProcessViewModel.cs
После переписывания обновлятора, она практически потеряла смысл, проще версию базы хранить в едином поле.
> Удаляем из параметров базы, отдельную настройку с микро обновлением.

- QS.Project.Gtk/Tdi/TdiSliderTab.cs
У всплывающего окна "Объект изменен. Сохранить изменения перед закрытием" нажатие на "крестик" обрабатывается аналогично нажатию "Отмена"
> Добавил обработку DeleteEvent

- Jenkinsfile
Дополнительно разобрался как сделать, чтобы тесты библиотек dotnet и net framework объединялись и показывались на дженкинсе вместе.
> Включил покрытие кода тестами для библиотека на dotnet

- QS.Project.Gtk/Widgets/ProgressWidget.cs
Из-за этого косяка прогресс на каждом шаге ждал 1 секунду. Поэтому все операции использующие это прогресс шли долго.
> Ускорение прогресса.

- QS.Project.Gtk/Views/Resolve/ClassNamesBaseGtkViewResolver.cs
Очень часто возникает ситуации когда мы во view имеем несколько вложенных view. Причем часто эти вложенные view могут быть разные в зависимости от дочерней viewModel. Раньше приходилось пробрасывать резольвер или scope autofac через viewmodel чтобы вьюшка смогла создать дочерний виждет. Это выглядит допонительной перегрузкой viewmodel, тем что не требуется. Поэтому эта возможность добавлена в сам резольвер.
Документация https://github.com/QualitySolution/QSProjects/wiki/%D0%94%D0%B8%D0%B0%D0%BB%D0%BE%D0%B3%D0%B8-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F#%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80
> Добавлена поддержка View со вторым аргументом в конструкторе

- QS.Project/Project.Journal/DataLoader/DynamicQueryLoader.cs
В журнале очень легко ошибиться и использовать в место переданного в метод uow загрузчика, общий Uow журнала. Обычно они отличаются только заглавными или строчными буквами. Но в последствии это приводить к случайным исключениям, так как запросы вызваниваются в своем потоке. При неправильном использовании журнал часто может работать нормально, то ошибку легко пропустить, в продакшен.
> Создаем исключение если запрос создан неправильно.

- QS.Project.Core/ViewModels/Dialog/DialogViewModelBase.cs
- QS.Project/ViewModels/DialogTabViewModelBase.cs
- QS.Project/ViewModels/TabViewModelBase.cs
Не вызываем Dispose у вьюмодели, если AskClose вернул false, т.е. вкладка не закрылась
> Устранение ISessionIsClosed

- QS.Project/Project.Journal/DataLoader/DynamicQueryLoader.cs
Временный срочный фикс JoinQueryOver.
При загрузке страницы в DataLoader запросы с JoinQueryOver (таких много), пример:
var fuelWriteoffQuery = uow.Session.QueryOver<FuelWriteoffDocument>(() => fuelWriteoffAlias)
.Left.JoinQueryOver(() => fuelWriteoffAlias.Cashier, () => cashierAlias)
возникает исключение InvalidCastException
Здесь в коде workQuery.UnderlyingCriteria будет являться Subcriteria и не может быть приведена к  CriteriaImpl.
> Фикс InvalidCastException в DataLoader для JoinQueryOver

- QS.Project.Gtk/Dialog/EntityDialogBase.cs
Во всех старых диалогах, на базе этого виджета, обнаружен эффект. Если кликнуть двойным кликом по кнопке сохранить. То первый клик выполняет начало сохранения, видимо в какой то момент, в процессе сохранения управления передается главному потоку который обрабатывает второй клик. Тем самым запускается два процесса сохранения. Один из них потом падает. Потому что к началу его выполнения uow  уже уничтожен. Засеривание кнопки сохранить после первого нажатия должно решать проблему.
> Исправление падения на NullReference

- QS.Project.Gtk/Dialog/EntityDialogBase.cs
Все таки бывают ситуации когда попадание в метод onTabColse, не закрывает вкладку. например когда не закрыты подчиненые вкладки. 
В этом случае надо назад активировать кнопку сохранения.
> Исправление засеривание кнопки Save

- QS.Project/Deletion/ReplaceEntity.cs
- QS.Project/QS.Project.csproj
- QSOrmProject/QSOrmProject.csproj
Ребята обратите внимание, изменение немного нарушает обратную совместимость. Но идеи там не сложно переписать, на нестатическую зависимость.
- Класс перемещен в новые библиотеки.
- Класс сделан не статическим, чтобы можно было использовать переданную конфигурацию удаления, а не единую для всего проекта.
- Добавлена опциональная возможность отображать прогресс операции
- Исправлен баг, в работе с коллекциями.
> Обновление класса замены ссылок на объекты

- QS.Project.Gtk/Project.Dialogs.GtkUI/JournalActions/PermissionControlledEditButton.cs
- QS.Project.Gtk/Project.Dialogs.GtkUI/PermissionControlledRepresentationJournal.cs
Добавил булевый параметр, если нужно кнопку Изменить и двойной клик проверять на права по просмотру, а не изменению
> Изменение доступности кнопки изменить в старом журнале

- QS.Project.Gtk/Journal.GtkUI/JournalView.cs
- QS.Project/Project.Journal/JournalAction.cs
При текущей логике дочерние элементы во всплывающем меню не отображались, возможно я что-то забыл указать.
Заменил событие Activated на ButtonPressEvent, т.к Activated почему-то срабатывало на дочерних элементах только при нажатии на правую кнопку мыши
Обновил код вызова действий журнала при нажатии на хоткей. Теперь действия выполняются только если они Visible и Sensitive
> Изменена логика создания дочерних элементов меню для всплывающего меню

- QS.LibsTest/BaseParameters/ParametersServiceTest.cs
- QS.Project/BaseParameters/ParametersService.cs
Думаю это может отразится на других типах тоже.
Иначе есть шанс что параметр будет сохранен на одной культуре а прочитан на другой. Что приведет к ошибкам.
Так же это исправляет тесты.
> Сохраняем в параметры базы значения с плавающей точкой в независимом от культуры формате.

- QSProjectsLib/Login.cs
Иногда пользователь может скопировать и вставить пароль в окно входа, не переключив раскладку на английскую, тогда не будет работать сочетание клавиш Ctrl+A в журнале.
> Переключение раскладки клавиатуры на английскую при запуске программы

- QS.Project.Core/Project.DB/IDataBaseInfo.cs
- QS.Project.Gtk/ErrorReporting/ErrorMsgDlg.cs
- QS.Project.Gtk/ErrorReporting/UnhandledExceptionHandler.cs
По смыслу он не относится только к десктопу, в Core мне кажется ему самое место.
К тому же, понадобилось получить информацию о базе в службах на сервере, а десктоп там не нужен.
> Перемещение IDatabaseInfo в QS.Project.Core

- Binding/Gamma.Binding/GtkWidgets/yTreeView.cs
Как выяснилось, на линуксе при старом варианте GTK обращался к модели, после того как мы ее очистили. Поэтому фикс просто сдвигает очистку на потом.
> Исправление падения при удалении модели.

- QS.Project.Gtk/Journal.GtkUI/JournalView.cs
- QS.Project/Project.Journal/JournalViewModelBase.cs
Возможность определить нужно ли раскрывать дерево после перезагрузки элементов
> Настройка для журналов (master)

- QS.Project.Desktop/Navigation/INavigationManager.cs
- QS.Project.Desktop/Navigation/IViewModelsPageFactory.cs
- QS.Project.Desktop/Navigation/NavigationManagerBase.cs
- QS.Project.Gtk/Navigation/AutofacViewModelsGtkPageFactory.cs
- QS.Project.Gtk/Navigation/AutofacViewModelsTdiPageFactory.cs
- QS.Project.Gtk/Navigation/TdiNavigationManager.cs
- QS.Project/Navigation/ITdiCompatibilityNavigation.cs
- QS.Project/Project.Filter/FilterViewModelBase.cs
- QS.Testing/Testing.Navigation/AutofacViewModelsFactoryForTests.cs
- добавил в некоторые методы навигатора необязательный экшен настройки вью модели. Полезно для журналов, когда надо добавить некоторые параметры до запуска фильтрации после инициализации вьюхи;
- плюс добавил метод конфигурации фильтра журнала без запуска фильтрации;
> Обновил навигатор и добавил метод в базовый класс фильтра журнала

- QS.HistoryLog/HibernateTracker.cs
Все равно далее для сохранения используется уже имеющаяся в этом классе строка подключения, поэтому считаю что доставать логин из переданного UoW нет нужды.
> Фикс ошибки сохранения истории изменений при закрытой сессии

- Modules/QSBanks/AccountsView.cs
Если редактирование счетов недоступно, то кнопки должны быть неактивны.
Но если в списке счетов выделить строку, то засеривание кнопок снимается и пользователь может удалить счет.
> Фикс снятия засеривания кнопок в виджете банковских счетов организации

- QS.Project.Gtk/Journal.GtkUI/JournalView.cs
- QS.Project/Project.Journal/DataLoader/AnyDataLoader.cs
- QS.Project/Project.Journal/DataLoader/IDataLoader.cs
- QS.Project/Project.Journal/DataLoader/ThreadDataLoader.cs
- QS.Project/Project.Journal/JournalViewModelBase.cs
1. После редактирования записи журнала загружать то же самое кол-во строк, что было перед редактированием.
2. После загрузки строк возвращаться на ту позицию, которая была до вызова диалога редактирования строки.
3. Исправлен баг, когда при скролле вместо одного следующего списка из 100 строк подгружается несколько раз по 100 строк.
> Фикс скролла в журналах

- QS.HistoryLog/Domain/FieldChange.cs
- QS.HistoryLog/HistoryObjectDesc.cs
- QS.Utilities/Extensions/TypeExtensions.cs
Исправление позволяет точно получить свойство без AmbiguousMatchException, в случаяъ когда в классе используется ствойство с модицикатором new и отличающимся типом от родительского свойства.
Но получает оно из класса который указывается в аргументе метода, родительские классы игнорируются.
> Фикс получения свойств у наследуемых классов

- .editorconfig
Для библиотеки этого параметра там быть не должно, так как если она используется как модуль, то корневым editorconfig в библиотеке - быть не может
> Исправлена ошибка в editorconfig

- QS.Project.Gtk/Widgets.GtkUI/DateRangePicker.cs
если есть дефолтные надписи в строке с датой то парсим ее соответствующим образом, иначе при потере фокуса при переключении вкладки, если этот виджет находится первым на странице, вместо заполненной стартовой даты, заполняются обе и начальная и конечная одним значением
> исправил логику парсинга даты

- QS.Project.Gtk/Journal.GtkUI/JournalView.cs
- QS.Project.Gtk/Tdi/TdiNotebook.cs
т.к. они приводят к падениям, в журналах слайдерах, при добавлении вновь созданной сущности и при работе с диалогами где есть стационарные фильтры
> убрал некоторые правки по утечкам

- QS.Extensions.Observable/Collections/List/ObservableList.cs
- QS.Extensions.Observable/Collections/List/PersistentGenericObservableBag.cs
специально реализуем интерфейс IList, чтобы можно было прикастить классы ObservableList и PersistanseObservableBag к IList без потери автообновления UI, т.к. будут также вызываться нужные события
> реализация интерфейса IList
